# Generated by Django 4.1 on 2022-11-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinus',
            name='user_email',
        ),
        migrations.AddField(
            model_name='joinus',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
