# Generated by Django 4.1 on 2022-10-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sermon',
            name='featured',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
