# Generated by Django 4.1 on 2022-11-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuch', '0005_alter_message_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
