# Generated by Django 4.1 on 2022-11-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuch', '0007_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
