# Generated by Django 4.1 on 2022-11-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuch', '0008_alter_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.CharField(choices=[('YOUTH', 'Youth_events'), ('MEN', 'Youth_events')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
