# Generated by Django 4.1 on 2022-11-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuch', '0009_remove_event_categories_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='categories',
            field=models.CharField(choices=[('BIBLESTUDY', 'BIBLESTUDY'), ('MIDWEEKSTUDY', 'MIDWEEKSTUDY'), ('MORNINGDEVOTION', 'MORNINGDEVOTION')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.CharField(choices=[('YOUTH', 'YOUTH'), ('MEN', 'MEN'), ('WOMEN', 'WOMEN'), ('CHILDREN', 'CHILDREN')], max_length=100),
        ),
    ]
