# Generated by Django 4.1 on 2022-11-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuch', '0010_sermon_categories_alter_event_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='categories',
            field=models.CharField(choices=[('SERMON', 'SERMON'), ('BIBLESTUDY', 'BIBLESTUDY'), ('MIDWEEKSTUDY', 'MIDWEEKSTUDY'), ('MORNINGDEVOTION', 'MORNINGDEVOTION')], max_length=100),
        ),
    ]
