# Generated by Django 4.1 on 2022-11-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuch', '0011_alter_sermon_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.CharField(choices=[('YOUTH', 'YOUTH'), ('MEN', 'MEN'), ('WOMEN', 'WOMEN'), ('CHILDREN', 'CHILDREN'), ('CHURCH', 'CHURCH')], max_length=100),
        ),
    ]
