# Generated by Django 4.1 on 2022-11-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chuch', '0012_alter_event_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('User_email', models.EmailField(max_length=70)),
            ],
        ),
    ]
