# Generated by Django 4.1 on 2022-11-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chuch', '0014_rename_user_email_joinus_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinUs',
        ),
    ]
